added some checks to the postinstall script.

diff --git a/postinstall b/postinstall
--- a/postinstall
+++ b/postinstall
@@ -1,8 +1,14 @@
 #!/bin/bash -l
 
+## check internet connectivity
+ping -q -w 1 -c 1 google.com > /dev/null || exit 1
+
+
+export TESTUSER=jenkins
+
 logic_which() {
     which $1 > /dev/null
-    return `echo $?`
+    return $?
 }
 export -f logic_which
 
@@ -18,7 +24,7 @@ os_dep_install() {
                 sudo apt-get install -y build-essential curl git python-setuptools ruby python-software-properties debconf-utils && \
                 sudo add-apt-repository -y ppa:webupd8team/java && \
                 sudo apt-get update && \
-                echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
+                echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections && \
                 sudo apt-get install -y oracle-java8-installer
         else
             echo "Unknown operating system"
@@ -28,22 +34,32 @@ export -f os_dep_install
 
 
 ## Install dependencies
-os_dep_install
-sudo useradd -md /home/jenkins jenkins
-sudo su - jenkins -c '
-umask 077
-mkdir -p ~/.ssh
-touch ~/.ssh/authorized_keys
-cat <<EOT >> ~/.ssh/authorized_keys
-ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGUlBDq5JXOLu/wdXTHLsVvbswiBYfBtVbxEgbol+VlB6zoy5lbjNkY7n/2YR2QJUjLjU4Z9dziVCIEMhmwZe9hgFsFZIaYIEX0DuJuIN0KRqE0VZlZCmuLgfsX6PjY14tshkBWGRshgYGZnIz2g/YGLxTOE7YNDA6SsF45Df5UEKp/EXul7IBpPz3Fu8D5Xr2aAi0fOTj9pCUSWPBapDD44d00E+JxaEf9PI6xW8SaTcJOtSGNOA5yZcJO2F6vhkZ6rF2JYIrcLU4FxaG90Q0HlAlHDpX5ARtRH1YRNgND2hBCxz4wKeTzJYv2Rx+AVOPjqLeOi8GUwKaebniBfnv jenkins
-ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCqFx7FVdx6TjaUybDbYyxPF4d+xDMDQn8CVcOVGvENcnp8pmaMuQfQE/1b6UW7T8Xg3e64+SLrx0pjPOPtyx0M+gK0AqTUL9lWm+vyBUM0Fb4po6FYydSxB04H4C0crJQbtpUFHhMth24vFHLemVjG9U/zsvQ+iR8bvkjEry7ZQB7W3fvnP5uDCy+e5T6BKwwUTp3pBxy+EWyVysWa/BN1WbkYtZHmSK7/OT81AIajcomAvpJF43rcvhOh/vH8gPlDBarFtxzU2DyAoQvJK0Hn3P5AD5U7B5R4J3PSQkPCTVurZ//wqukyOXA0GI6JRJai8sM+a6bn8LVpHTgciyr jenkins@10.254.144.104
+if ! os_dep_install ; then echo "Dependencies installation failed"; exit 1; fi | tee -a postinstall.log
+if ! `sudo useradd -md /home/$TESTUSER -s /bin/bash $TESTUSER` ; then echo "User creation failed"; exit 1; fi | tee -a postinstall.log
+
+if !    `sudo su - $TESTUSER -c '
+            umask 077
+            mkdir -p ~/.ssh
+            touch ~/.ssh/authorized_keys
+            cat <<EOT >> ~/.ssh/authorized_keys
+            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGUlBDq5JXOLu/wdXTHLsVvbswiBYfBtVbxEgbol+VlB6zoy5lbjNkY7n/2YR2QJUjLjU4Z9dziVCIEMhmwZe9hgFsFZIaYIEX0DuJuIN0KRqE0VZlZCmuLgfsX6PjY14tshkBWGRshgYGZnIz2g/YGLxTOE7YNDA6SsF45Df5UEKp/EXul7IBpPz3Fu8D5Xr2aAi0fOTj9pCUSWPBapDD44d00E+JxaEf9PI6xW8SaTcJOtSGNOA5yZcJO2F6vhkZ6rF2JYIrcLU4FxaG90Q0HlAlHDpX5ARtRH1YRNgND2hBCxz4wKeTzJYv2Rx+AVOPjqLeOi8GUwKaebniBfnv jenkins
+            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCqFx7FVdx6TjaUybDbYyxPF4d+xDMDQn8CVcOVGvENcnp8pmaMuQfQE/1b6UW7T8Xg3e64+SLrx0pjPOPtyx0M+gK0AqTUL9lWm+vyBUM0Fb4po6FYydSxB04H4C0crJQbtpUFHhMth24vFHLemVjG9U/zsvQ+iR8bvkjEry7ZQB7W3fvnP5uDCy+e5T6BKwwUTp3pBxy+EWyVysWa/BN1WbkYtZHmSK7/OT81AIajcomAvpJF43rcvhOh/vH8gPlDBarFtxzU2DyAoQvJK0Hn3P5AD5U7B5R4J3PSQkPCTVurZ//wqukyOXA0GI6JRJai8sM+a6bn8LVpHTgciyr jenkins@10.254.144.104
 EOT
+'`
+    then
+        echo "Adding public keys failed"
+        exit 1
+fi | tee -a postinstall.log
+
 
 ## Brew installation
+sudo su - $TESTUSER -c '
 git clone --depth 1 https://github.com/Linuxbrew/brew.git ~/.linuxbrew
 export PATH="$HOME/.linuxbrew/bin:$PATH"
 brew tap homebrew/test-bot
+'
 
+sudo su - $TESTUSER -c '
 cat <<EOT >> ~/.bashrc
 export PATH="$HOME/.linuxbrew/bin:$PATH"
 export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
@@ -52,4 +68,4 @@ EOT
 '
 
 ## Print IP address of the machine
-ip addr list|grep inet
+ip addr list | grep inet | tee -a postinstall.log
